### ISSUE TITLE
USBD_LL_Init() overwrites BTABLE?

### ISSUE THREAD

**Issue by dl8aau** [majbthrd/stm32cdcuart#1]
Hello Peter,

first of all many thanks for providing a composite driver that tries to be "universal" and works around
the horrible limitations of the original code.

You try to compute the PMA addresses in USBD_LL_Init() and you start at 0.
"pma_address = 0;"

The examples of STM however use the "magic" constant 0x18 and one wonders why...
The reason is the BTABLE, that starts at 0 and 8 bytes are needed per endpoint.
Look at #define PCD_EP_TX_ADDRESS
With your definition I think you overwrite the BTABLE.

One easy fix would be to initialze pma_address to the max. endpoint number (there should be enough space...). Doing it dynamically would require a different approach (you would need to compute first the number of endpoints).

Regards,

Alexander

**Comment by majbthrd** [comment]
Thanks for catching this!  I've updated this and my other STM32 GitHub projects.  I opted for the more foolproof scheme of presuming all endpoints in the USB peripheral might be used.
