### ISSUE TITLE
Maximum UART baudrate?

### ISSUE THREAD

**Issue by andysworkshop** [majbthrd/stm32cdcuart#3]
What do think a practical maximum baudrate would be with this code, assuming DMA is used to and from the UART? I notice that you code a default of 115.2k and I'd like to achieve 230.4k if possible. This code could be the reason I need to ditch the MCP2221A that I normally use and save some space on my board.

**Comment by majbthrd** [comment]
For what it is worth, I'm using it for similar board space and BOM cost reasons and at UART rates around 1Mbps/s.

However, having said that, I would encourage you to test, test, and test again things for your particular application.  The STM32F072B-DISCO eval board is cheap ($11 USD), so even if you don't have your own hardware yet, initial prototyping of things for your particular OSes and hardware is very feasible.  This doesn't indicate a lack of confidence in the firmware, but rather reflects a war-weary perspective that there can be many, many different PC, OS, and driver version combinations out there.

One bandwidth test that I do is to jumper the UART pins for loopback on the hardware (eval board or custom), and then use the PC to write data as quickly as possible into the port and also read back the returning data.  (Spot-checking the loopback jumper with a scope during this throughput test to verify no gapping between bytes is also a desirable test.)  These tests should be repeated on all the various OSes and PC driver versions you expect to encounter.  If there are going to be multiple ports, then these ports should be tested concurrently.

You will also want to verify that the particular UART bit rates you want work well with the UART divisors on the STM32.  This should be a non-issue for 230.4k, but I'm mentioning this in case someone else reads this in future.  Also, there is ultimately a USB 1.1 bandwidth issue with enough ports or very high bit rates (but that is yet another reason to perform the throughput tests above).

Playing devil's advocate, the advantage of buying an off-the-shelf solution like a MCP2221A, FTDI, etc. is that you have some expectation of someone else having done testing of this already for you.  Another advantage is to have signed Windows drivers.  (At least with Windows XP and Windows 7, using CDC serial ports requires paying fees for driver signing and acquiring a valid USB VID:PID.  I have no idea what extra complications exist for MacOS.  Linux has no driver issues, but some distributions lock up the ports for the first 30 seconds trying to use the device as a dial-up modem unless a udev rule is created.)  Life is just easier when someone else can take the blame for a problem (and hopefully come up with a solution).  Chips like FTDI's also have fast built-in XON/XOFF support in hardware (whereas stm32cdcuart and the underlying STM32 do not).

It is a cost-benefit tradeoff that you must make for your particular application, and hopefully the above helps you.

**Comment by majbthrd** [comment]
P.S.: if doing a hardware design-in, I encourage you to look at taking advantage of the BOOT0 pin on the STM32F0x2.  The part has a built-in DFU bootloader (in mask ROM), which saves the pain of having to either preprogram the parts or provide a connector on the PCB to program the part after assembly.  FYI, I also have an "elf2dfuse" project to ease creation of DFU update files for the STM32.

**Comment by andysworkshop** [comment]
Thank you very much for the prompt response with all the detailed tips. It is much appreciated. At the time of writing I had compiled and flashed your code as-is to the 072 disco board and verified an enumerate-disconnect-enumerate cycle then I thought I'd contact you to check if it was going to perform as I'd hoped. It's great to hear that you're using it at much higher rates than I need.

My peer is Linux, which doesn't perform particularly well at very high baud rates, presumably due to the OS occasionally deciding it wants to do something else during a serial port operation. Above a few hundred kbaud I start to see random loss of synchronization during frames. You have to get really defensive in the way you code the sender/receiver.

Thanks for the tip about DFU. I hadn't even considered that and will now implement a way to pull BOOT0  high on reset without an operator present so I can do remote firmware updates.
