### ISSUE TITLE
Maximum number of uarts?

### ISSUE THREAD

**Issue by dave2** [majbthrd/stm32cdcuart#5]
Some STM32 devices have quite a few UARTS available, but I've never seen more than 2 for any CDC configuration. Is it reasonable to try 4-8 UARTs accepting that there will be some contention at FS (but maybe less of a problem with HS?)

Thanks!

**Comment by majbthrd** [comment]
I don't know about your "never seen more than 2" claim, as if you look carefully, you'll see that this project supports *three* CDC UARTs.  Three is the maximum possible concurrently with the STM32F072.

You must consider not just the number of UART peripherals available on the STM32 of interest, but also:

a)	the number of USB endpoints, and
b)	the number of distinct DMA channels that can be used for UART purposes

You'll have to dig into the Reference Manual of the STM32 of interest (as the Data Sheet is too high level for this).  In the case of the STM32F072, RM0091 states in the USB Chapter: "Configurable number of endpoints from 1 to 8" and later "up to 16 mono-directional or 8 bidirectional endpoints can be used".

As you can see in ./src/usbd_desc.c (look for "CDC_DESCRIPTOR("), there are four mono-directional endpoints needed for every CDC port.  The basic USB interface needs two endpoints as well (EP0 IN and EP0 OUT).  2 + 3 * 4 = 14, and 14 <= 16

The other area to look in the Reference Manual is in the DMA Chapter.  Look in the "Summary of the DMA requests for each channel", you'll see that (at least for the STM32F072) there are only seven DMA channels.  Two are needed for each UART direction (RX and TX), so once again you are limited to three CDC UARTs.  2 * 3 = 6, and 6 <= 7.  Read the "Sanity Checklist If Customizing" section of the README.md for specifics.
